const centros = [
  {
    name: "Eduardo Houellemont, LMHC, Ma",
    latitude: 18.468238,
    longitude: -69.931351,
    id: 42940,
    phone_number: "829-708-1111 y 809-901-8063",
    address: "Plaza La Francesa, Ave. A. Lincoln, suite 345",
    logo: "https://s3.eu-west-1.amazonaws.com/staticd.psico.org/logos/c68c135a10991a386e7cd54cd073084d_300.jpg",
    service: "Premium",
    url_center: "https://www.psico.org/centro-42940",
    draw_stars:
      '<i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i>',
  },
  {
    name: "Daniel Carreras",
    latitude: 18.464193,
    longitude: -69.933279,
    id: 62348,
    phone_number: "8093333353",
    address: "Av 27 de Febrero en Santo Domingo, Rep\u00fablica Dominicana",
    logo: "https://www.psico.org/img/logo-default.png",
    service: "Premium",
    url_center: "https://www.psico.org/centro-62348",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "ALEJANDRA DI VIETRO, Psicologa Clinica, M.A",
    latitude: 18.456838,
    longitude: -69.950579,
    id: 61457,
    phone_number: null,
    address:
      "Plaza Central ,Suite 401 ,  Av.  27 de Febrero esq.  Winston Churchill. SD",
    logo: "https://s3.eu-west-1.amazonaws.com/staticd.psico.org/logos/af94ece07e39f873207ef9d2051bf2e1_300.jpeg",
    service: "Premium",
    url_center: "https://www.psico.org/centro-61457",
    draw_stars:
      '<i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i>',
  },
  {
    name: "Daniel Carreras, MA      PSICOCONSULTAS",
    latitude: 18.463679,
    longitude: -69.934806,
    id: 61273,
    phone_number: "8099028033",
    address: "Av. 27 de febrero Plaza Central local 401, Santo Domingo D.N.",
    logo: "https://s3.eu-west-1.amazonaws.com/staticd.psico.org/logos/9c592df8f95e3d2d6fc14f5870b81456_300.jpg",
    service: "Premium",
    url_center: "https://www.psico.org/centro-61273",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Lic. Jean Carlos Santos S\u00e1nchez",
    latitude: 18.468485,
    longitude: -69.932009,
    id: 60092,
    phone_number: "1 (809) 542-2022; 1-829-605-1576",
    address: "Plaza La Francesa 3er nivel, Av. Abraham Lincoln, Santo Domingo",
    logo: "https://s3.eu-west-1.amazonaws.com/staticd.psico.org/logos/d02cda25888c7f91866faa680ae24bc8_300.jpeg",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-60092",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Psicolog\u00eda humanista  Integral",
    latitude: 18.472347,
    longitude: -69.895645,
    id: 49024,
    phone_number: "809-964-8880",
    address: "calle uruguay # 5 gazcue.",
    logo: "https://www.psico.org/img/logo-default.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-49024",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Licda.Lisse Morales Pinales",
    latitude: 18.486057,
    longitude: -69.931213,
    id: 39276,
    phone_number: "8292815473",
    address:
      "Av. Independencia casi esquina Benito Monci\u00f3n E, Edif. Do Pico Marginal 3er. Piso, Gazcue. ",
    logo: "https://s3.eu-west-1.amazonaws.com/staticd.psico.org/logos/nuevo_logo_39276.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-39276",
    draw_stars:
      '<i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i><i class="fas fa-star text-default"></i>',
  },
  {
    name: "Lic. Jeanette Slagt de Gonzalez",
    latitude: 18.469482,
    longitude: -69.915176,
    id: 5723,
    phone_number: "809-687-7164",
    address: "Cap. Eugenio de Marchena no. 35, Torre Juliana Consuelo, 3-B",
    logo: "https://www.psico.org/img/logo-default.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-5723",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "ISPE",
    latitude: 18.486057,
    longitude: -69.931213,
    id: 24896,
    phone_number: "809-687-1824",
    address: "Cesar Nicolas Penson #31, Gazcue",
    logo: "https://www.psico.org/img/logo-default.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-24896",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Lic. Vincent Guerrero Lluberes",
    latitude: 18.469868,
    longitude: -69.980774,
    id: 17557,
    phone_number: "809-683-9038",
    address: "Evaristo Morales, Poligono Central.",
    logo: "https://s3.eu-west-1.amazonaws.com/staticd.psico.org/logos/12bd8aff4313af0068e404dbca7ab1ad_300.jpeg",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-17557",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Dra P. Brito. 8099647015",
    latitude: 18.46899,
    longitude: -69.905266,
    id: 10647,
    phone_number: "8099647015, 8094336577",
    address: "CM Gazcue",
    logo: "https://www.psico.org/img/logo-default.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-10647",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Consult Psicologia Clinica MDS",
    latitude: 19.307134,
    longitude: -69.553136,
    id: 36017,
    phone_number: "829 994-6119/809 810-8616",
    address: "Fabio Abreu 80, La Ceiba",
    logo: "https://s3.eu-west-1.amazonaws.com/staticd.psico.org/logos/nuevo_logo_36017.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-36017",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Yesmin Meyer",
    latitude: 18.468233,
    longitude: -69.93222,
    id: 52192,
    phone_number: "809-542-2022",
    address: "Plaza La Francesa Tercer Nivel, suite 345",
    logo: "https://www.psico.org/img/logo-default.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-52192",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Peach. Multiservices",
    latitude: 18.44747,
    longitude: -69.9608,
    id: 36232,
    phone_number: "+18099630530",
    address: "San Juan Bautista de La Salle #35, Avenida Privada ",
    logo: "https://www.psico.org/img/logo-default.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-36232",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
  {
    name: "Ana Herrero",
    latitude: 18.469967,
    longitude: -69.948898,
    id: 27801,
    phone_number: "809-729.1250",
    address: "C/. 8 no. 16. ",
    logo: "https://www.psico.org/img/logo-default.png",
    service: "Gratuito",
    url_center: "https://www.psico.org/centro-27801",
    draw_stars:
      '<i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>',
  },
];
